fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    puppet: "#{source_dir}"
