---
  .travis.yml:
    hc_secure: "iSPprJS+t7TDKKHdvr2pRcMe51IlYvjOz+BzC2Ih3R9gkLFHjqLgCemGAi6Ab1URjRuhe8rb0RK1gDb0DHlrWMp0PVQTJyKH+67saK3eWZC59fKW1eJtjHgiMNYzmmi+Yq0zOhUnLILU/D77KvImn5T0bWp2L6OW0XXxoJOTEj4="
